In [1]:
import pandas as pd
import urllib as ul

# from Bio import Entrez

**Part Two [25 marks]**

 - 15 marks for successfully completing the tasks.
 - up to 6 marks for including one additional piece of analysis.
 - up to 4 marks for exceptionally well organised and executed approach.

Next we want to look at some of the functional terms that have been annotated to SFARI genes separating them out by their gene-score.

## Task 1

Map the gene-symbol for every gene in the SFARI gene list to an NCBI UID (unique Entrez Gene identifier) (2 marks).

In [2]:
SFARI_gene = pd.read_csv('SFARI-Gene_genes_10-29-2020release_11-22-2020export.csv')

print(len(SFARI_gene))
SFARI_gene.head()

992

,status,gene-symbol,gene-name,ensembl-id,chromosome,genetic-category,gene-score,syndromic,number-of-reports
0,9,ABAT,4-aminobutyrate aminotransferase,ENSG00000183044,16,"Rare Single Gene Mutation, Genetic Association",3.0,0,5
1,9,ABCA10,"ATP-binding cassette, sub-family A (ABC1), mem...",ENSG00000154263,17,Rare Single Gene Mutation,3.0,0,1
2,9,ABCA13,ATP binding cassette subfamily A member 13,ENSG00000179869,7,"Rare Single Gene Mutation, Functional",3.0,0,6
3,9,ABCA7,"ATP-binding cassette, sub-family A (ABC1), mem...",ENSG00000064687,19,Rare Single Gene Mutation,3.0,0,4
4,9,ACE,angiotensin I converting enzyme,ENSG00000159640,17,"Rare Single Gene Mutation, Genetic Association",3.0,0,3

I used the Gene information of Homo Sapiens which was found here: 

https://ftp.ncbi.nlm.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz 

to link the gene symbols to the gene IDs.

In [3]:
# retrieve the Homo_sapiens file
# ul.request.urlretrieve('https://ftp.ncbi.nlm.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz','Homo_sapiens.gene_info.gz')

Homo = pd.read_csv('Homo_sapiens.gene_info.gz', compression='gzip', header=0, sep='\t')

Homo.head()

,#tax_id,GeneID,Symbol,LocusTag,Synonyms,dbXrefs,chromosome,map_location,description,type_of_gene,Symbol_from_nomenclature_authority,Full_name_from_nomenclature_authority,Nomenclature_status,Other_designations,Modification_date,Feature_type
0,9606,1,A1BG,-,A1B|ABG|GAB|HYST2477,MIM:138670|HGNC:HGNC:5|Ensembl:ENSG00000121410,19,19q13.43,alpha-1-B glycoprotein,protein-coding,A1BG,alpha-1-B glycoprotein,O,alpha-1B-glycoprotein|HEL-S-163pA|epididymis s...,20201124,-
1,9606,2,A2M,-,A2MD|CPAMD5|FWP007|S863-7,MIM:103950|HGNC:HGNC:7|Ensembl:ENSG00000175899,12,12p13.31,alpha-2-macroglobulin,protein-coding,A2M,alpha-2-macroglobulin,O,alpha-2-macroglobulin|C3 and PZP-like alpha-2-...,20201124,-
2,9606,3,A2MP1,-,A2MP,HGNC:HGNC:8|Ensembl:ENSG00000256069,12,12p13.31,alpha-2-macroglobulin pseudogene 1,pseudo,A2MP1,alpha-2-macroglobulin pseudogene 1,O,pregnancy-zone protein pseudogene,20201124,-
3,9606,9,NAT1,-,AAC1|MNAT|NAT-1|NATI,MIM:108345|HGNC:HGNC:7645|Ensembl:ENSG00000171428,8,8p22,N-acetyltransferase 1,protein-coding,NAT1,N-acetyltransferase 1,O,arylamine N-acetyltransferase 1|N-acetyltransf...,20201124,-
4,9606,10,NAT2,-,AAC2|NAT-2|PNAT,MIM:612182|HGNC:HGNC:7646|Ensembl:ENSG00000156006,8,8p22,N-acetyltransferase 2,protein-coding,NAT2,N-acetyltransferase 2,O,arylamine N-acetyltransferase 2|N-acetyltransf...,20201124,-

In [4]:
Map = pd.merge(SFARI_gene, Homo, left_on = 'gene-symbol', right_on = 'Symbol')
Map = pd.DataFrame(Map, columns = ['GeneID', 'gene-symbol', 'gene-score'])

print(len(Map))
Map.head()

985

   GeneID gene-symbol  gene-score
0      18        ABAT         3.0
1   10349      ABCA10         3.0
2  154664      ABCA13         3.0
3   10347       ABCA7         3.0
4    1636         ACE         3.0

## Task 2

Using the gene2go file from NCBI that we worked with in week 8 find the Gene Ontology terms that have been annotated to all of the SFARI genes (4marks).

In [5]:
# retrieve the gene2go file
# ul.request.urlretrieve('https://ftp.ncbi.nlm.nih.gov/gene/DATA/gene2go.gz','gene2go.gz')

gene2go = pd.read_csv('gene2go.gz', compression='gzip', header=0, sep='\t')

gene2go.head()

,#tax_id,GeneID,GO_ID,Evidence,Qualifier,GO_term,PubMed,Category
0,3702,814629,GO:0005634,ISM,-,nucleus,-,Component
1,3702,814629,GO:0008150,ND,-,biological_process,-,Process
2,3702,814630,GO:0003700,ISS,-,DNA-binding transcription factor activity,11118137,Function
3,3702,814630,GO:0005634,ISM,-,nucleus,-,Component
4,3702,814630,GO:0006355,TAS,-,"regulation of transcription, DNA-templated",11118137,Process

In [6]:
GO_terms = pd.merge(Map, gene2go, on = 'GeneID')
# GO_terms = pd.DataFrame(GO_terms, columns = ['GeneID', 'gene-symbol', 'GO_term', 'gene-score']).drop_duplicates().groupby('GeneID')
GO_terms = pd.DataFrame(GO_terms, columns = ['GeneID', 'GO_ID', 'gene-symbol', 'GO_term', 'gene-score'])

print(len(GO_terms))
GO_terms.head()

26898

,GeneID,GO_ID,gene-symbol,GO_term,gene-score
0,18,GO:0001666,ABAT,response to hypoxia,3.0
1,18,GO:0003867,ABAT,4-aminobutyrate transaminase activity,3.0
2,18,GO:0005739,ABAT,mitochondrion,3.0
3,18,GO:0005739,ABAT,mitochondrion,3.0
4,18,GO:0005739,ABAT,mitochondrion,3.0

## Task 3

Now split the genes up into three lists by their SFARI gene-score (1 mark).

In [7]:
GO_terms_split = GO_terms.groupby('gene-score')

GO_terms_1 = GO_terms_split.get_group(1)
GO_terms_2 = GO_terms_split.get_group(2)
GO_terms_3 = GO_terms_split.get_group(3)

GO_terms_1.head()

,GeneID,GO_ID,gene-symbol,GO_term,gene-score
553,23394,GO:0000785,ADNP,chromatin,1.0
554,23394,GO:0000981,ADNP,"DNA-binding transcription factor activity, RNA...",1.0
555,23394,GO:0003677,ADNP,DNA binding,1.0
556,23394,GO:0005507,ADNP,copper ion binding,1.0
557,23394,GO:0005515,ADNP,protein binding,1.0

In [8]:
GO_terms_1.to_csv('GO_terms_1.csv')
GO_terms_2.to_csv('GO_terms_2.csv')
GO_terms_3.to_csv('GO_terms_3.csv')

## Task 4

Create tables of the 10 most commonly annotated terms for each gene list. The tables should have the following columns: GO term ID, GO term Description, GO term count (3 marks).

In [9]:
# gene-score: 1
GO_top10_1 = pd.merge(pd.DataFrame(GO_terms_1, columns = ['GO_ID', 'GO_term']), pd.DataFrame(GO_terms_1.value_counts('GO_term'), columns = ['GO_term_count']), on = 'GO_term').sort_values(by = 'GO_term_count', ascending = False).drop_duplicates()
# pd.DataFrame(GO_terms_1.value_counts('GO_term'), columns = ['GO_term_count']).iloc[1:11]

GO_top10_1.to_csv('GO_1.csv')
GO_top10_1.iloc[1:11]

,GO_ID,GO_term,GO_term_count
337,GO:0005634,nucleus,142
1367,GO:0005654,nucleoplasm,122
957,GO:0005886,plasma membrane,90
711,GO:0005829,cytosol,83
459,GO:0005737,cytoplasm,66
1804,GO:0045944,positive regulation of transcription by RNA po...,57
13,GO:0000785,chromatin,50
515,GO:0006357,regulation of transcription by RNA polymerase II,47
68,GO:0000981,"DNA-binding transcription factor activity, RNA...",46
1594,GO:0000122,negative regulation of transcription by RNA po...,44

In [10]:
# gene-score: 2
GO_top10_2 = pd.merge(pd.DataFrame(GO_terms_2, columns = ['GO_ID', 'GO_term']), pd.DataFrame(GO_terms_2.value_counts('GO_term'), columns = ['GO_term_count']), on = 'GO_term').sort_values(by = 'GO_term_count', ascending = False).drop_duplicates()

GO_top10_2.to_csv('GO_2.csv')
GO_top10_2.iloc[1:11]

           GO_ID                                GO_term  GO_term_count
357   GO:0005886                        plasma membrane            117
286   GO:0005634                                nucleus             97
655   GO:0005829                                cytosol             93
927   GO:0005737                              cytoplasm             75
1161  GO:0005654                            nucleoplasm             73
959   GO:0005887  integral component of plasma membrane             37
489   GO:0016020                               membrane             34
1041  GO:0016021         integral component of membrane             33
1239  GO:0070062                  extracellular exosome             28
1579  GO:0098978                  glutamatergic synapse             27

In [11]:
# gene-score: 3
GO_top10_3 = pd.merge(pd.DataFrame(GO_terms_3, columns = ['GO_ID', 'GO_term']), pd.DataFrame(GO_terms_3.value_counts('GO_term'), columns = ['GO_term_count']), on = 'GO_term').sort_values(by = 'GO_term_count', ascending = False).drop_duplicates()

GO_top10_3.to_csv('GO_3.csv')
GO_top10_3.iloc[1:11]

,GO_ID,GO_term,GO_term_count
598,GO:0005886,plasma membrane,245
2289,GO:0005829,cytosol,193
1885,GO:0005634,nucleus,163
2018,GO:0005737,cytoplasm,148
2783,GO:0005654,nucleoplasm,141
2546,GO:0005887,integral component of plasma membrane,95
411,GO:0016021,integral component of membrane,88
3179,GO:0016020,membrane,75
258,GO:0046872,metal ion binding,67
3909,GO:0000981,"DNA-binding transcription factor activity, RNA...",62

## Task 5

Take the three lists of UIDs created above and use the PantherDB tool - http://pantherdb.org/ to perform a “Functional classification viewed in graphic charts” analysis reporting and select the “Bar chart” display option, using default settings. Once on the results page displaying the bar chart use the pull-down menu to change the ontology to “Biological Process”. Click the small (!) “export” button to download the results as a text file and us this to make your own bar chart (5 marks).

In [12]:
UID_list = Map.groupby('gene-score')

UID_list_1 = pd.DataFrame(UID_list.get_group(1), columns = ['GeneID'])
UID_list_1.to_csv('UID_list_1.csv')

UID_list_2 = pd.DataFrame(UID_list.get_group(2), columns = ['GeneID'])
UID_list_2.to_csv('UID_list_2.csv')

UID_list_2 = pd.DataFrame(UID_list.get_group(3), columns = ['GeneID'])
UID_list_2.to_csv('UID_list_3.csv')

## Requirement

Compare and contrast your results from Tasks 4 and 5 and any differences you find between the gene lists from the different gene-score categories in the SFARI gene lists. What can you say about Autism genes based on the results from these analyses?

Possible extensions here might be to explore other pathway analysis tools and websites such as KEGG and Reactome. You could also chose to perform a statistical analysis directly on the results from Task 4.